---
apiVersion: opentestfactory.org/v1alpha1
kind: Workflow
metadata:
    name: Robot Execute
    defaults:
        runs-on: robotframework
jobs:
    thisIsASuccess:
        runs-on: robotframework
        steps:
        -  uses: actions/checkout@v2
           with:
              repository: https://github.com/SquashTF-workshop/robotDemoXML
        -  uses: robotframework/execute@v1
           with:
               test: robotDemoXML/demo-xml.robot#Execute Basic Tests
    thisIsAFailure:
        runs-on: robotframework
        needs: thisIsASuccess
        steps:
        -  uses: actions/checkout@v2
           with:
              repository: https://github.com/SquashTF-workshop/robotTFParamCheck
        -  uses: robotframework/execute@v1
           with:
               test: robotTFParamCheck/robot_community.robot#Check Default Param Failure
